CREATE DATABASE 'localhost:C:\dev\base.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8;

-- Cadastro de Clientes
CREATE TABLE CLIENTES (
    CLIENTE_ID INTEGER NOT NULL,
    TIPO_PESSOA CHAR(1) NOT NULL,
    CPF_CNPJ VARCHAR(14) NOT NULL,
    NOME VARCHAR(60),
    CEP CHAR(8),
    LOGRADOURO VARCHAR(60),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(40),
    REFERENCIA VARCHAR(40),
    BAIRRO VARCHAR(60),
    CIDADE VARCHAR(60),
    UF CHAR(2),
    CODIGO_IBGE CHAR(7)
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY (CLIENTE_ID);

CREATE SEQUENCE SEQ_CLIENTE_ID;

CREATE OR ALTER TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  NEW.CLIENTE_ID = GEN_ID(SEQ_CLIENTE_ID, 1);
end;

-- Cadastro de Produtos
CREATE TABLE PRODUTOS (
    PRODUTO_ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(255),
    UNIDADE CHAR(2),
    PRECO_VENDA DOUBLE PRECISION
);

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY (PRODUTO_ID);

CREATE SEQUENCE SEQ_PRODUTO_ID;

CREATE OR ALTER TRIGGER PRODUTOS_BI0 FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  NEW.PRODUTO_ID = GEN_ID(SEQ_PRODUTO_ID, 1);
end;

-- PEDIDO
CREATE TABLE PEDIDOS (
    PEDIDO_ID INTEGER NOT NULL,
    REFERENCIA VARCHAR(40),
    NUMERO_PEDIDO VARCHAR(10),
    DATA_EMISSAO TIMESTAMP,
    CLIENTE_ID INTEGER,
    TIPO_OPERACAO CHAR(1),
    VALOR_TOTAL DOUBLE PRECISION);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS
PRIMARY KEY (PEDIDO_ID);

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_1
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID);

CREATE SEQUENCE SEQ_PEDIDO_ID;

CREATE OR ALTER TRIGGER PEDIDOS_BI0 FOR PEDIDOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  NEW.PEDIDO_ID = GEN_ID(SEQ_PEDIDO_ID, 1);
end;

-- Itens do Pedido
CREATE TABLE PEDIDOS_ITENS (
    PEDIDO_ITEM_ID INTEGER NOT NULL,
    PEDIDO_ID INTEGER NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    UNIDADE CHAR(2),
    QUANTIDADE NUMERIC(9,4),
    VALOR_UNITARIO NUMERIC(18,4),
    TOTAL NUMERIC(18,4)
);

ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT PK_PEDIDOS_ITENS
PRIMARY KEY (PEDIDO_ITEM_ID);

ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_1
FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(PEDIDO_ID)
ON DELETE CASCADE;

ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_2
FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID)
ON DELETE CASCADE;

CREATE SEQUENCE SEQ_PEDIDO_ITEM_ID;

CREATE OR ALTER TRIGGER PEDIDOS_ITENS_BI0 FOR PEDIDOS_ITENS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  NEW.PEDIDO_ITEM_ID = GEN_ID(SEQ_PEDIDO_ITEM_ID, 1);
end;